name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: build with dotnet
      run: dotnet build ./src/PlainApiGateway.sln --configuration Release
    - name: test with dotnet
      run: dotnet test ./src/Solution.sln --configuration Release
