name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build with dotnet
      run: dotnet build ./src/PlainApiGateway.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./src/PlainApiGateway.sln --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput="$github.workspace/lcov.info"
    - name: Install coveralls.net
      run: dotnet tool install --global coveralls.net --version 1.0.0
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: ${{ github.workspace }}/lcov.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
