name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build with dotnet
      run: dotnet build ./src/PlainApiGateway.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./src/PlainApiGateway.sln --configuration Release /p:CollectCoverage=true
    - name: Install coveralls.net
      run: dotnet tool install --global coveralls.net --version 1.0.0
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
